name: GitHub Pages

on:
  push:
    branches:
      - main
#     paths: src/**
#   pull_request:
#     branches: [ main ]
#     paths: src/**
  workflow_dispatch:

# permissions:
#   contents: read
#   issues: read
#   checks: write
#   pull-requests: write
#   pages: write
#   #id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: src
    
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
      
      # https://github.com/marketplace/actions/docfx-action
      - name: ⚙ docfx-action
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: src/docfx.json
      
      # https://github.com/marketplace/actions/github-pages-action
      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/_site
